#report: "report/workflow.rst"

configfile: 'config/config.yaml'

include : 'rules/common.smk'
include : 'rules/preprocess.smk'
include : 'rules/cluster.smk'

rule all:
    input:
        all_outputs()
