import yaml

#configfile: "config/config.yaml"

#SENSORS = ['screen','calls', 'steps', 'sleep']
SENSORS = ['screen']

rule all:
    input:
        expand('../data/interim/tesserae/{sensor}_4epochs.csv', sensor=SENSORS)

rule extract:
    input:
        '/scratch/cs/tesserae/postprocessed/{sensor}.parquet'
    output:
        '../data/interim/tesserae/{sensor}_4epochs.csv'
#    params:
#        sensor = config["sensor"]
    script:
        '{wildcards.sensor}.py'