name: Sync fig/ from P1 into P2

on:
  push:
    branches: [main, master]

permissions:
  contents: write

concurrency:
  group: sync-fig
  cancel-in-progress: true

jobs:
  sync:
    # avoid loops from the bot's own push
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      P1_URL: https://github.com/lnknguyen/digirhythm
      P1_BRANCH: main          # change if P1 uses a different default branch
      SRC_DIR: fig
      DST_DIR: fig

    steps:
      - name: Checkout P2 (this repo)
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # uses GITHUB_TOKEN to push back

      - name: Clone P1 (public via HTTPS)
        run: |
          git clone --depth 1 "$P1_URL" p1
          cd p1
          git checkout "$P1_BRANCH" || true

      - name: Mirror fig/ from P1 to P2 (including deletions)
        run: |
          mkdir -p "${DST_DIR}"
          rsync -av --delete "p1/${SRC_DIR}/" "${DST_DIR}/"

      - name: Commit & push if there are changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain -- ${DST_DIR})" ]; then
            git add "${DST_DIR}"
            git commit -m "chore(fig): sync ${DST_DIR} from P1 (${P1_BRANCH})"
            git push origin HEAD
          else
            echo "No fig/ changes to commit."
          fi

