name: Sync P2 fig/ → P1 fig/ (SSH)

on:
  push:
    branches: [main, master]

permissions:
  contents: read   # only for this repo (P2)

concurrency:
  group: sync-fig-to-p1
  cancel-in-progress: true

jobs:
  sync:
    # This job runs when you push to P2; it pushes to P1 over SSH.
    runs-on: ubuntu-latest
    env:
      P1_SSH_URL: git@github.com:lnknguyen/digirhythm.git
      P1_BRANCH: main
      SRC_DIR: figures
      DST_DIR: publication-figs

    steps:
      - name: Checkout P2
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # we push to P1 with SSH, not to P2

      - name: Start ssh-agent and add deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.P1_DEPLOY_KEY }}

      - name: Trust github.com host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts

      - name: Clone P1 via SSH (will use the deploy key)
        run: |
          git clone --depth 1 "$P1_SSH_URL" p1
          cd p1
          git checkout "$P1_BRANCH" || true

      - name: Mirror P2/fig → P1/fig (including deletions)
        run: |
          mkdir -p "p1/${DST_DIR}"
          rsync -av --delete "${SRC_DIR}/" "p1/${DST_DIR}/"

      - name: Commit & push to P1 if changed
        run: |
          cd p1
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin "$P1_BRANCH" || true
          if [ -n "$(git status --porcelain -- ${DST_DIR})" ]; then
            git add "${DST_DIR}"
            git commit -m "chore(fig): mirror from lnknguyen/digirhythm-v2 @ $GITHUB_SHA"
            git push origin HEAD:"$P1_BRANCH"
          else
            echo "No changes to push to P1."
          fi

